#! /bin/sh
cabal run . -- $1 --no-text-deco

status=$?

if [ $status -ne 0 ]; then
    exit $status
fi

file_name=$(basename "$1")
file_base_name="${file_name%.*}"

mv $file_base_name.s $file_base_name.unix.S
gcc -E $file_base_name.unix.S > $file_base_name.s