#! /bin/sh
cabal run wacc25 -- $1 --no-text-deco --target-unix

status=$?

if [ $status -ne 0 ]; then
    exit $status
fi

file_name=$(basename "$1")
file_base_name="${file_name%.*}"

mv $file_base_name.S $file_base_name.macro.S
gcc -E $file_base_name.macro.S > $file_base_name.s
